# --- TYPES ---

type User {
    id: ID!
    email: String!
    username: String
    avatar: String
    subscription: String # "FREE", "PRO", "FAMILY"
}

type AuthPayload {
    token: String!
    user: User!
}

type ListParticipant {
    username: String
    avatar: String
    lastSeen: String
}

type ShoppingItem {
    id          : ID!
    name        : String!
    quantity    : Float
    unit        : String
    category    : String
    dueDate     : String
    comment     : String
    priceStore1 : Float
    priceStore2 : Float
    userPrice   : Float
    completed   : Boolean!
    imageUrl    : String
    addedBy: String
    addedByAvatar: String
    completedBy: String
    completedByAvatar: String
}

type ShoppingList {
    id    : ID!
    name  : String!
    owner : String # Email владельца
    items : [ShoppingItem]!
    participants: [ListParticipant]
    messages: [ChatMessage]
}

type ChatMessage {
    id: ID
    sender: String
    avatar: String
    text: String
    timestamp: String
}

# --- INPUTS ---

input UserInput {
    username: String!
    avatar: String
}

input AddItemInput {
    name: String!
    quantity: Float
    unit: String
    category: String
    dueDate: String
    comment: String
    priceStore1: Float
    priceStore2: Float
    userPrice: Float
}

input UpdateItemInput {
    name: String
    quantity: Float
    unit: String
    category: String
    dueDate: String
    comment: String
    priceStore1: Float
    priceStore2: Float
    userPrice: Float
    imageUrl: String
}

# --- QUERY ---

type Query {
    allLists: [ShoppingList]!
    listById(id: ID!, user: UserInput): ShoppingList
    searchImages(query: String!): [String]!
}

# --- MUTATION ---

type Mutation {
    # Auth
    requestLoginCode(email: String!): Boolean!
    loginWithCode(email: String!, code: String!): AuthPayload!
    updateUserProfile(username: String!, avatar: String!): User!

    # Subscription (НОВОЕ)
    updateUserSubscription(plan: String!): User!

    # Lists
    createList(name: String!): ShoppingList!
    addItem(listId: ID!, itemInput: AddItemInput!, user: UserInput!): ShoppingItem!
    updateItem(listId: ID!, itemId: ID!, itemInput: UpdateItemInput!): ShoppingItem!
    removeItem(listId: ID!, itemId: ID!): Boolean!
    toggleItem(listId: ID!, itemId: ID!, completed: Boolean!, user: UserInput!): ShoppingItem!
    sendMessage(listId: ID!, text: String!, user: UserInput!): ChatMessage!
}

# --- SUBSCRIPTION ---

type Subscription {
    listUpdated(listId: ID!): ShoppingList
}