spring.application.name=backend

spring.data.mongodb.uri=mongodb://localhost:27017/smartshop

spring.graphql.graphiql.enabled=true

google.api.key=AIzaSyC1x0N-LFsi_PDBFy2jvZdWiJN4JmUBpj4
google.cx =c145b753e6beb4130

google.cloud.project-id=proj-shopping-list
google.cloud.location=us-central1
google.cloud.ai.model=gemini-2.5-flash
